<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ARMSAccountDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR03-ARMSAccount/ARMSAccountDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR03-ARMSAccount/ARMSAccountDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/ARMSAccountDB">
   <plt:partnerLinkType name="ARMSAccountDB_plt">
      <plt:role name="ARMSAccountDB_role">
         <plt:portType name="tns:ARMSAccountDB_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/ARMSAccountDB" schemaLocation="xsd/ARMSAccountDB_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="AccountCollection_msg">
      <wsdl:part name="AccountCollection" element="top:AccountCollection"/>
   </wsdl:message>
   <wsdl:portType name="ARMSAccountDB_ptt">
      <wsdl:operation name="merge">
         <wsdl:input message="tns:AccountCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
