<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PrepareAccountAck" targetNamespace="http://xmlns.oracle.com/ARIS_KPEI_PROJECT/OR03_ARMSAccount/PrepareAccountAck" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.oracle.com/ARIS_KPEI_PROJECT/OR03_ARMSAccount/PrepareAccountAck" xmlns:ns1="http://www.kpei.co.id/schema/Account.001" xmlns:ns2="http://www.kpei.co.id/ResponseMessage" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.kpei.co.id/schema/Account.001" schemaLocation="xsd/ARMSAccount-request.xsd"/>
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.kpei.co.id/ResponseMessage" schemaLocation="xsd/ResponseMessage.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="PrepareAccountAckRequestMessage">
      <wsdl:part name="payload" element="ns1:AccountToARMS"/>
   </wsdl:message>
   <wsdl:message name="PrepareAccountAckResponseMessage">
      <wsdl:part name="payload" element="ns2:ResponseMessage"/>
   </wsdl:message>
   <wsdl:portType name="PrepareAccountAck">
      <wsdl:operation name="process">
         <wsdl:input message="client:PrepareAccountAckRequestMessage"/>
         <wsdl:output message="client:PrepareAccountAckResponseMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="PrepareAccountAck">
      <plnk:role name="PrepareAccountAckProvider">
         <plnk:portType name="client:PrepareAccountAck"/>
      </plnk:role>
   </plnk:partnerLinkType>
</wsdl:definitions>
